[package]
name = "amclient"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11"
csv = "1.1.6"
kafka = "0.9.0"
bevy_quinnet = "0.5"
serde = "1.0.152"